# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4364c12b0ae1c0eb06adf7ed160f8c1ab02cf6fc95ffa79524be3a68f6c420ef1c99d4ca402d1ff60ac98588a02e503c6c68ac40b2f35dc6bf218c242330779

test:
  secret_key_base: 5d412c3d0cd9b0cc29ddb4a3b9160823930346405f588ed0add297fe50cc4caa3ccfc909b79f8979838e340c74270b6458fff397a374a35f451f520b3dbb14d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
